Set the JAVA_HOME environment variable for maven 3 tasks
jfrog/bamboo-artifactory-plugin pull request #100
Opened 2020-02-28 21:29 UTC by clarkperkins

2020-06-11 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jfrog/bamboo-artifactory-plugin?pullRequest=100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jfrog/bamboo-artifactory-plugin?pullRequest=100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jfrog/bamboo-artifactory-plugin?pullRequest=100) it.</sub>

2020-10-21 13:04 UTC, yahavi requested changes
Thanks for your contribution @clarkperkins!
We like to merge your code.

I have 1 comment - we already call `getConfiguredJdkPath` in the buildCommand->getJavaExecutable. In order to avoid resolving the JDK path twice, I suggest to pass it to the buildCommand and getJavaExecutable functions.

Please let me know if you're going to implement it or whether you want we take it from here.
Thanks!

2020-10-21 13:52 UTC, clarkperkins commented
Hi @yahavi, I've made the requested changes!

2020-10-21 14:32 UTC, yahavi approved these changes
Perfect. Thanks a lot for your contribution @clarkperkins!

2020-10-21 14:36 UTC, merged