Add docker pull and push tasks
jfrog/bamboo-artifactory-plugin pull request #118
Opened 2020-10-19 06:45 UTC by barbelity

2020-10-19 07:12 UTC, yahavi requested changes
I just reviewed the shared credentials parts. Please see my comments.

2020-10-19 07:12 UTC, yahavi commented on src/main/resources/atlassian-plugin.xml
> +        <configuration class="org.jfrog.bamboo.configuration.ArtifactoryDockerConfiguration"/>
Please add the runtimeTaskDataProvider
```suggestion
        <configuration class="org.jfrog.bamboo.configuration.ArtifactoryDockerConfiguration"/>
        <runtimeTaskDataProvider class="org.jfrog.bamboo.security.provider.SharedCredentialsDataProvider"/>

```

2020-10-19 07:12 UTC, yahavi commented on src/main/resources/templates/plugins/task/editArtifactoryDockerBuilder.ftl
> +        var credentialsUserName = configDiv.getElementsByTagName('input')[1].value;
```suggestion
        var credentialsUserName = configDiv.getElementsByTagName('input')[2].value;
```

2020-10-19 07:12 UTC, yahavi commented on src/main/resources/templates/plugins/task/editArtifactoryDockerBuilder.ftl
> +        var credentialsPassword = configDiv.getElementsByTagName('input')[2].value;
```suggestion
        var credentialsPassword = configDiv.getElementsByTagName('input')[3].value;
```

2020-10-19 07:20 UTC, barbelity commented on src/main/resources/atlassian-plugin.xml
> +        <configuration class="org.jfrog.bamboo.configuration.ArtifactoryDockerConfiguration"/>
Added.

2020-10-21 11:40 UTC, yahavi requested changes
Very good!
Please consider to delete `viewArtifactoryDeploymentAction.ftl` as well.

2020-10-21 11:40 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/configuration/ArtifactoryDockerConfiguration.java
> +        String commandChoiceKey = NpmBuildContext.COMMAND_CHOICE;
```suggestion
        String commandChoiceKey = COMMAND_CHOICE;
```

2020-10-21 11:40 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/context/DockerBuildContext.java
> +        return (ArtifactoryDockerConfiguration.CFG_DOCKER_COMMAND_PULL.equals(env.get(COMMAND_CHOICE)));
Redundant parenthesis
```suggestion
        return ArtifactoryDockerConfiguration.CFG_DOCKER_COMMAND_PULL.equals(env.get(COMMAND_CHOICE));
```

2020-10-22 08:41 UTC, barbelity commented on src/main/java/org/jfrog/bamboo/configuration/ArtifactoryDockerConfiguration.java
> +        String commandChoiceKey = NpmBuildContext.COMMAND_CHOICE;
Fixed.

2020-10-22 08:41 UTC, barbelity commented on src/main/java/org/jfrog/bamboo/context/DockerBuildContext.java
> +        return (ArtifactoryDockerConfiguration.CFG_DOCKER_COMMAND_PULL.equals(env.get(COMMAND_CHOICE)));
Fixed.

2020-10-22 09:22 UTC, barbelity commented
> Very good!
> Please consider to delete `viewArtifactoryDeploymentAction.ftl` as well.

You are correct, removed `viewArtifactoryDeploymentAction.ftl`.
Thanks 👍

2020-10-22 09:31 UTC, merged